import{useEffect,useState}from"react";
const hero=[
"https://images.unsplash.com/photo-1786052338245-f64eb727c37c?auto=format&fit=crop&fm=jpg&q=90&w=2400",
"https://images.unsplash.com/photo-1781758333991-c5c59ca7673d?auto=format&fit=crop&fm=jpg&q=90&w=2400",
"https://images.unsplash.com/photo-1786310146649-283be8896b36?auto=format&fit=crop&fm=jpg&q=90&w=2400"
];
const collections=[
["Gold Jewellery","Tradition in every detail",hero[0]],
["Diamond Jewellery","Brilliance for every occasion",hero[1]],
["Silver Jewellery","Grace for everyday",hero[2]],
["Bridal Collection","For your special day","https://images.unsplash.com/photo-1705326454933-9685fc6888e1?auto=format&fit=crop&fm=jpg&q=90&w=2400"]
];
const gallery=[...hero,...collections.map(x=>x[2])];
function App(){const[i,setI]=useState(0);const[menu,setMenu]=useState(false);useEffect(()=>{const t=setInterval(()=>setI(x=>(x+1)%hero.length),5000);return()=>clearInterval(t)},[]);
return <><header><div className="wrap nav"><a className="brand" href="#"><b>✦ Poornima Jewellers</b><small>Elegance · Trust · Tradition</small></a><nav>{["Collections","About","Gallery","Appointment"].map(x=><a href={"#"+x.toLowerCase()} key={x}>{x}</a>)}</nav><button className="hamb" onClick={()=>setMenu(!menu)}>{menu?"✕":"☰"}</button></div>{menu&&<div className="mobile">{["Collections","About","Gallery","Appointment"].map(x=><a onClick={()=>setMenu(false)} href={"#"+x.toLowerCase()} key={x}>{x}</a>)}</div>}</header>
<section className="hero"><div className="slides">{hero.map((x,k)=><div key={x} className={"slide "+(k===i?"active":"")} style={{backgroundImage:`url(${x})`}}/> )}</div><div className="shade"/><div className="wrap heroText"><small>POORNIMA JEWELLERS</small><h1>Jewellery that feels <span>beautifully yours.</span></h1><p>Timeless gold, diamond and silver jewellery for weddings, celebrations and everyday elegance.</p><div className="actions"><a className="btn gold" href="#collections">Explore Collections</a><a className="btn outline" href="#appointment">Book a Consultation</a></div></div><div className="dots">{hero.map((_,k)=><button key={k} className={k===i?"on":""} onClick={()=>setI(k)}/>)}</div></section>
<section className="trust wrap"><div>💎<b>Certified Quality</b><small>Hallmarked jewellery</small></div><div>🤝<b>Trusted Service</b><small>Personal guidance</small></div><div>✨<b>Wide Collection</b><small>Gold, diamond & silver</small></div><div>❤️<b>Made for Moments</b><small>Bridal & gifting</small></div></section>
<section className="section wrap" id="collections"><small className="eyebrow">OUR COLLECTIONS</small><h2>A piece for every precious moment.</h2><div className="grid cards">{collections.map(([t,s,img])=><article className="card" key={t}><img src={img}/><div><b>{t}</b><small>{s}</small></div></article>)}</div></section>
<section className="section alt" id="about"><div className="about wrap"><img src={gallery[4]} /><div><small className="eyebrow">THE POORNIMA EXPERIENCE</small><h2>More than jewellery. A memory you keep forever.</h2><p>Every piece is chosen to feel personal — from the first sparkle you love to the jewellery you pass down one day.</p><a className="btn gold" href="#appointment">Book a Consultation</a></div></div></section>
<section className="section wrap" id="gallery"><small className="eyebrow">FEATURED GALLERY</small><h2>Moments that sparkle.</h2><div className="grid gallery">{gallery.map((x,k)=><img key={k} src={x} loading="lazy"/>)}</div></section>
<section className="section alt" id="appointment"><div className="appointment wrap"><div><small className="eyebrow">PRIVATE CONSULTATION</small><h2>Make your visit memorable.</h2><p>Send us your requirement on WhatsApp.</p></div><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const text=`Hello Poornima Jewellers,\n\nName: ${f.get("name")}\nPhone: ${f.get("phone")}\nLooking for: ${f.get("interest")}\nMessage: ${f.get("message")}`;window.open("https://wa.me/919000000000?text="+encodeURIComponent(text),"_blank")}}><input name="name" placeholder="Your Name" required/><input name="phone" placeholder="Phone Number" required/><select name="interest"><option>Gold Jewellery</option><option>Diamond Jewellery</option><option>Silver Jewellery</option><option>Bridal Collection</option></select><textarea name="message" placeholder="What are you looking for?"/><button className="btn gold">Send on WhatsApp</button></form></div></section>
<section className="section wrap contact"><h2>Visit Poornima Jewellers</h2><p>Bengaluru, Karnataka</p><div className="actions"><a className="btn gold" href="https://www.google.com/maps/search/?api=1&query=Poornima%20Jewellers%20Bengaluru" target="_blank">📍 Directions</a><a className="btn outlineDark" href="tel:+919000000000">📞 Call</a><a className="btn wa" href="https://wa.me/919000000000" target="_blank">💬 WhatsApp</a></div></section>
<footer><div className="wrap"><b>Poornima Jewellers</b><p>Timeless jewellery for celebrations, milestones and everyday moments.</p><small>© 2026 Poornima Jewellers. All rights reserved.</small></div></footer></>}export default App;